# Generated by Django 6.0.7 on 2026-07-31 09:55

import django.db.models.deletion
import django_core_micha.messaging.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_key', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('keyset_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group'), ('broadcast', 'Broadcast'), ('managed', 'Managed'), ('object_thread', 'Object thread')], max_length=16)),
                ('title', django_core_micha.messaging.fields.EncryptedTextField(app_key_accessor='messaging_app_key', blank=True, null=True)),
                ('external_key', models.CharField(blank=True, max_length=128, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('retention_policy', models.CharField(choices=[('never', 'Never')], default='never', max_length=16)),
                ('delete_after', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_high', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messaging_conversations_high', to=settings.AUTH_USER_MODEL)),
                ('user_low', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messaging_conversations_low', to=settings.AUTH_USER_MODEL)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='django_core_micha_messaging.messagingapp')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('last_message_at'), descending=True, nulls_last=True), '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('chat', 'Chat'), ('announcement', 'Announcement'), ('poll', 'Poll'), ('system', 'System')], default='chat', max_length=16)),
                ('title', django_core_micha.messaging.fields.EncryptedTextField(app_key_accessor='messaging_app_key', blank=True, null=True)),
                ('body', django_core_micha.messaging.fields.EncryptedTextField(app_key_accessor='messaging_app_key', blank=True, null=True)),
                ('link_target', django_core_micha.messaging.fields.EncryptedTextField(app_key_accessor='messaging_app_key', blank=True, null=True)),
                ('client_request_id', models.UUIDField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='django_core_micha_messaging.conversation')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_deleted_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='django_core_micha_messaging.message')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blob_key', django_core_micha.messaging.fields.EncryptedTextField(app_key_accessor='messaging_app_key')),
                ('filename', django_core_micha.messaging.fields.EncryptedTextField(app_key_accessor='messaging_app_key')),
                ('content_type', models.CharField(max_length=128)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_key', django_core_micha.messaging.fields.EncryptedTextField(app_key_accessor='messaging_app_key', blank=True, null=True)),
                ('scan_state', models.CharField(choices=[('unscanned', 'Unscanned'), ('clean', 'Clean'), ('rejected', 'Rejected'), ('error', 'Error')], default='unscanned', max_length=16)),
                ('scan_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='django_core_micha_messaging.message')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='django_core_micha_messaging.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageThreadReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_read_at', models.DateTimeField()),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_receipts', to='django_core_micha_messaging.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_thread_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessagingAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('target_object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('reason', models.TextField(blank=True)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_audit_events', to=settings.AUTH_USER_MODEL)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='django_core_micha_messaging.messagingapp')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MessagingScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('container', 'Container'), ('object', 'Object'), ('global', 'Global')], max_length=16)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='django_core_micha_messaging.messagingapp')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='django_core_micha_messaging.messagingscope'),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', django_core_micha.messaging.fields.EncryptedTextField(app_key_accessor='messaging_app_key')),
                ('allow_multiple', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_created_polls', to=settings.AUTH_USER_MODEL)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='django_core_micha_messaging.message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', django_core_micha.messaging.fields.EncryptedTextField(app_key_accessor='messaging_app_key')),
                ('order', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='django_core_micha_messaging.poll')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='django_core_micha_messaging.polloption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membership_source', models.CharField(choices=[('manual', 'Manual'), ('provider', 'Provider')], default='manual', max_length=16)),
                ('last_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('muted', models.BooleanField(default=False)),
                ('email_enabled', models.BooleanField(blank=True, null=True)),
                ('push_enabled', models.BooleanField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='django_core_micha_messaging.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('conversation', 'user'), name='msg_participant_pair_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'sender', 'client_request_id'), name='msg_client_request_uniq'),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'user', 'emoji'), name='msg_reaction_uniq'),
        ),
        migrations.AddConstraint(
            model_name='messagethreadreceipt',
            constraint=models.UniqueConstraint(fields=('root', 'user'), name='msg_thread_receipt_uniq'),
        ),
        migrations.AddIndex(
            model_name='messagingauditevent',
            index=models.Index(fields=['app', 'created_at'], name='msg_audit_app_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagingscope',
            constraint=models.UniqueConstraint(fields=('app', 'kind', 'content_type', 'object_id'), name='msg_scope_app_kind_object_uniq'),
        ),
        migrations.AddConstraint(
            model_name='messagingscope',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content_type__isnull', True), ('kind', 'global'), ('object_id__isnull', True)), models.Q(('content_type__isnull', False), ('kind__in', ['container', 'object']), ('object_id__isnull', False)), _connector='OR'), name='msg_scope_ref_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'direct')), fields=('app', 'scope', 'user_low', 'user_high'), name='msg_direct_app_scope_pair_uniq'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['managed', 'broadcast'])), fields=('app', 'scope', 'kind', 'external_key'), name='msg_managed_bcast_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'direct'), ('user_high__isnull', False), ('user_low__isnull', False)), models.Q(('kind', 'direct'), _negated=True), _connector='OR'), name='msg_direct_has_canonical_pair'),
        ),
        migrations.AddConstraint(
            model_name='pollvote',
            constraint=models.UniqueConstraint(fields=('option', 'user'), name='msg_poll_vote_uniq'),
        ),
    ]
