# Generated by Django 6.0.7 on 2026-08-01 14:00

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def preserve_legacy_group_duplicates(apps, schema_editor):
    """Retain the earliest keyed group; later legacy duplicates become ad-hoc rows.

    Group conversations were not previously covered by the partial unique
    constraint. Nulling the later keys preserves every conversation and its
    participants while making the canonical earliest row reusable by the key.
    """
    Conversation = apps.get_model('django_core_micha_messaging', 'Conversation')
    duplicate_keys = (
        Conversation.objects.filter(kind='group', external_key__isnull=False)
        .values('app_id', 'scope_id', 'external_key')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    for key in duplicate_keys.iterator():
        duplicate_ids = list(
            Conversation.objects.filter(
                app_id=key['app_id'], scope_id=key['scope_id'], kind='group', external_key=key['external_key'],
            ).order_by('created_at', 'id').values_list('id', flat=True)[1:]
        )
        Conversation.objects.filter(id__in=duplicate_ids).update(external_key=None)


class Migration(migrations.Migration):

    dependencies = [
        ('django_core_micha_messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='msg_managed_bcast_key_uniq',
        ),
        migrations.RunPython(preserve_legacy_group_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['managed', 'group', 'broadcast'])), fields=('app', 'scope', 'kind', 'external_key'), name='msg_managed_bcast_key_uniq'),
        ),
    ]
