# Generated by Django 6.0.7 on 2026-08-04 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('bucket_start', models.DateTimeField()),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('last_ping_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['app_key', 'content_type', 'object_id', 'bucket_start'], name='activity_bucket_scope_range_ix')],
                'constraints': [models.UniqueConstraint(fields=('app_key', 'content_type', 'object_id', 'user', 'bucket_start'), name='activity_bucket_scope_user_bucket_uniq')],
            },
        ),
    ]
