# Generated by Django 6.0.5 on 2026-07-18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_core_micha_notifications", "0002_notification_notificationrecipient_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannelDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(max_length=16)),
                ("enabled", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "channel"],
                        name="notif_chdefault_user_channel",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "channel"),
                        name="uniq_notification_channel_default",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationCategoryChannelPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=32)),
                ("channel", models.CharField(max_length=16)),
                ("enabled", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "category", "channel"],
                        name="notif_catpref_user_cat_channel",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "category", "channel"),
                        name="uniq_notification_category_channel",
                    ),
                ],
            },
        ),
    ]
