# Generated by Django 6.0.5 on 2026-07-18

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("django_core_micha_notifications", "0003_notification_channel_defaults"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notificationdelivery",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.UniqueConstraint(
                condition=Q(digest_threshold__isnull=True),
                fields=("recipient", "channel"),
                name="uniq_notification_delivery_no_threshold",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.UniqueConstraint(
                condition=Q(digest_threshold__isnull=False),
                fields=("recipient", "channel", "digest_threshold"),
                name="uniq_notification_delivery_with_threshold",
            ),
        ),
    ]
