# Generated by Django 6.0.5 on 2026-07-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_core_micha_notifications", "0004_notificationdelivery_partial_unique_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.CharField(max_length=64)),
                ("type_key", models.CharField(max_length=64)),
                ("enabled", models.BooleanField(default=True)),
                ("lead_days_override", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content_type", "object_id", "type_key"),
                        name="uniq_todo_override_scope_type",
                    ),
                ],
            },
        ),
    ]
