# Generated by Django 6.0.7 on 2026-08-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_core_micha_notifications', '0006_todooverride_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='push_preview_opt_in',
            field=models.BooleanField(default=True),
        ),
    ]
